# Generated by Django 3.0.4 on 2020-03-27 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pothole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pothole_point', models.TextField()),
                ('create_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'pothole',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PotholeLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
                ('submit_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'pothole_ledger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=64)),
                ('pword', models.CharField(max_length=128)),
                ('is_admin', models.IntegerField()),
            ],
            options={
                'db_table': 'site_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VwPothole',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('pothole_point', models.TextField()),
                ('create_date', models.DateTimeField()),
                ('effective_date', models.CharField(blank=True, max_length=76, null=True)),
                ('fixed_date', models.CharField(blank=True, max_length=76, null=True)),
                ('pothole_reports', models.DecimalField(blank=True, decimal_places=0, max_digits=23, null=True)),
                ('fixed_reports', models.DecimalField(blank=True, decimal_places=0, max_digits=23, null=True)),
            ],
            options={
                'db_table': 'vw_pothole',
                'managed': False,
            },
        ),
    ]
